/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  size: 'small' | 'medium' | 'large' | 'custom250';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    custom250?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            body?:
              | (
                  | {
                      value?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'text';
                    }
                  | {
                      file?: (string | null) | Media;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'gif';
                    }
                  | {
                      file?: (string | null) | Media;
                      position?: ('right' | 'center' | 'left') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image_center';
                    }
                  | {
                      buttonText?: string | null;
                      url: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'buttonText';
                    }
                  | {
                      value?: string | null;
                      position?: ('right' | 'center' | 'left') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'moderText';
                    }
                )[]
              | null;
            images?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content_header';
          }
        | {
            body?:
              | (
                  | {
                      value?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'text';
                    }
                  | {
                      file?: (string | null) | Media;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'gif';
                    }
                  | {
                      file?: (string | null) | Media;
                      position?: ('right' | 'center' | 'left') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image_center';
                    }
                  | {
                      buttonText?: string | null;
                      url: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'buttonText';
                    }
                  | {
                      value?: string | null;
                      position?: ('right' | 'center' | 'left') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'moderText';
                    }
                )[]
              | null;
            images?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content_header_2';
          }
        | {
            body?:
              | (
                  | {
                      value?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'title';
                    }
                  | {
                      value?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'text';
                    }
                  | {
                      file?: (string | null) | Media;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'gif';
                    }
                  | {
                      file?: (string | null) | Media;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content_Body';
          }
        | {
            sliders?:
              | {
                  value?: string | null;
                  url?: string | null;
                  file?: (string | null) | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'card';
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Servicios';
          }
        | {
            titulo?: string | null;
            bloques?:
              | {
                  date?: string | null;
                  Title?: string | null;
                  value?: string | null;
                  url?: string | null;
                  file?: (string | null) | Media;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'card';
                }[]
              | null;
            botones?:
              | {
                  texto?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Tendencias';
          }
        | {
            titulo?: string | null;
            contenido?: string | null;
            logos?:
              | {
                  imagen: string | Media;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Datos_Formulario';
          }
        | {
            titulo: string;
            inputs?:
              | {
                  'place holder': string;
                  id?: string | null;
                }[]
              | null;
            boton: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            'Quienes somos': {
              titulo?: string | null;
              content?: string | null;
              file?: (string | null) | Media;
              boton: string;
              url: string;
            };
            Mision?: {
              titulo?: string | null;
              content?: string | null;
              file?: (string | null) | Media;
              background?: (string | null) | Media;
            };
            Vision?: {
              titulo?: string | null;
              content?: string | null;
              file?: (string | null) | Media;
              background?: (string | null) | Media;
            };
            chavoSaltando?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'Quienes somos';
          }
        | {
            Nombre: string;
            Correo: string;
            Telefono: string;
            Asunto: 'consulta' | 'soporte' | 'otros';
            Mensaje: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dekmfer';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  size?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        custom250?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        content_header?:
          | T
          | {
              body?:
                | T
                | {
                    text?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                          blockName?: T;
                        };
                    gif?:
                      | T
                      | {
                          file?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image_center?:
                      | T
                      | {
                          file?: T;
                          position?: T;
                          id?: T;
                          blockName?: T;
                        };
                    buttonText?:
                      | T
                      | {
                          buttonText?: T;
                          url?: T;
                          id?: T;
                          blockName?: T;
                        };
                    moderText?:
                      | T
                      | {
                          value?: T;
                          position?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              images?: T;
              id?: T;
              blockName?: T;
            };
        content_header_2?:
          | T
          | {
              body?:
                | T
                | {
                    text?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                          blockName?: T;
                        };
                    gif?:
                      | T
                      | {
                          file?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image_center?:
                      | T
                      | {
                          file?: T;
                          position?: T;
                          id?: T;
                          blockName?: T;
                        };
                    buttonText?:
                      | T
                      | {
                          buttonText?: T;
                          url?: T;
                          id?: T;
                          blockName?: T;
                        };
                    moderText?:
                      | T
                      | {
                          value?: T;
                          position?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              images?: T;
              id?: T;
              blockName?: T;
            };
        content_Body?:
          | T
          | {
              body?:
                | T
                | {
                    title?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                          blockName?: T;
                        };
                    text?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                          blockName?: T;
                        };
                    gif?:
                      | T
                      | {
                          file?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          file?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        Servicios?:
          | T
          | {
              sliders?:
                | T
                | {
                    card?:
                      | T
                      | {
                          value?: T;
                          url?: T;
                          file?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        Tendencias?:
          | T
          | {
              titulo?: T;
              bloques?:
                | T
                | {
                    card?:
                      | T
                      | {
                          date?: T;
                          Title?: T;
                          value?: T;
                          url?: T;
                          file?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              botones?:
                | T
                | {
                    texto?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        Datos_Formulario?:
          | T
          | {
              titulo?: T;
              contenido?: T;
              logos?:
                | T
                | {
                    imagen?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              titulo?: T;
              inputs?:
                | T
                | {
                    'place holder'?: T;
                    id?: T;
                  };
              boton?: T;
              id?: T;
              blockName?: T;
            };
        'Quienes somos'?:
          | T
          | {
              'Quienes somos'?:
                | T
                | {
                    titulo?: T;
                    content?: T;
                    file?: T;
                    boton?: T;
                    url?: T;
                  };
              Mision?:
                | T
                | {
                    titulo?: T;
                    content?: T;
                    file?: T;
                    background?: T;
                  };
              Vision?:
                | T
                | {
                    titulo?: T;
                    content?: T;
                    file?: T;
                    background?: T;
                  };
              chavoSaltando?: T;
              id?: T;
              blockName?: T;
            };
        dekmfer?:
          | T
          | {
              Nombre?: T;
              Correo?: T;
              Telefono?: T;
              Asunto?: T;
              Mensaje?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  menu?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  'Boton-Derecho': {
    Text: string;
    url: string;
    logo_?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo: string | Media;
  footerSections?:
    | {
        logo?: (string | null) | Media;
        content?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        url?: string | null;
        logo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  menu?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  'Boton-Derecho'?:
    | T
    | {
        Text?: T;
        url?: T;
        logo_?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  footerSections?:
    | T
    | {
        logo?: T;
        content?: T;
        url?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        url?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}